config/routes.rb
Rails.application.routes.draw do

  resources :interfaces
  devise_for :users
  scope '/admin' do
    resources :users
    resources :admincas
  end
  resources :posts
  resources :roles
  resources :users
  resources :tags
  get 'filter/:tag', to: 'posts#index', as: :ftags
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  validates :name, presence: true
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

# Tags controller class
class TagsController < ApplicationController
  load_and_authorize_resource
  def index
    @tags = Tag.all
    @taging = Tagging.all
  end

  # POST /tags or /tags.json
  def create
    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_form.html.erb
<%= simple_form_for @tag do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Role</h1>
<div class="wrapper fadeInDown">
  <div id="formContent">
    <%= render 'form', tag: @tag %>

    <%= link_to 'Back', tags_path %>
  </div>
</div>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= link_to 'New Tag', new_tag_path %>

<table>
  <tbody>
  <% @tags.each do |tag| %>
    <section class="pb-4">
      <div class="bg-white border rounded-5">

        <section class="p-2 d-flex  w-100" style="background-color: #fbfbfb; border-radius: .5rem .5rem 0 0;">
          <!--Section: News of the day-->
          <div class="col-md-2 mb-2">
            <h4><strong>Tags: <%= tag.name %></strong></h4>
            <%= link_to 'Show', tag %>
            <%= link_to 'Edit', edit_tag_path(tag) %>

            <br>
            <% if @taging.find { |val| val.tag_id == tag.id }.nil? %>
              Tag is not used anywhere:
              <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </section>
      </div>
    </section>
  <% end %>
  </tbody>
</table>

<br>

app/views/tags/new.html.erb
<h1>New Role</h1>

<div class="wrapper fadeInDown">
  <div id="formContent">
    <%= render 'form', tag: @tag %>

    <%= link_to 'Back', tags_path %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="wrapper fadeInDown">
  <div id="formContent">
    <p>
      <strong>Name:</strong>
      <%= @tag.name %>
    </p>


    <%= link_to 'Edit', edit_tag_path(@tag) %> |
    <%= link_to 'Back', tags_path %>
  </div>
</div>