config/routes.rb
Rails.application.routes.draw do

  resources :interfaces
  devise_for :users
  scope '/admin' do
    resources :users
    resources :admincas
  end
  resources :posts
  resources :roles
  resources :users
  resources :tags
  get 'filter/:tag', to: 'posts#index', as: :ftags
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  has_many :taggings
  has_many :tags, through: :taggings
  before_save :assign_post_type

  validates :title, presence: true, length: { in: 10..100 }
  validates :content, presence: true
  validates :post_type, presence: true

  def assign_post_type
    self.post_type = 'C' if post_type.nil?
  end

  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Posts controller class
class PostsController < ApplicationController
  load_and_authorize_resource

  # GET /posts or /posts.json
  def index
    @posts = if params[:tag]
               Post.tagged_with(params[:tag]).where(post_type: 'P').paginate(page: params[:page], per_page: 3)
             else
               Post.where(post_type: 'P').paginate(page: params[:page], per_page: 3)
             end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts or /posts.json
  def create
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description, :post_type, :user_id, :content, :tag_list, :tag,
                                 { tag_ids: [] }, :tag_ids)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if post.post_type == 'C' && !@current_user&.admin? || post.post_type.nil? %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.rich_text_area :content %>
    </div>

    <%= form.input :tag_ids, as: :select, collection: Tag.order(:name), label_method: :name, input_html: { multiple: true } %>

    <br>
  <% end %>

  <% if @current_user&.admin? %>

    <div class="field">
      <%= form.label :approved %>
      <%= form.check_box :post_type, { checked: false }, 'A', 'R' %>
    </div>
  <% elsif post.post_type == 'AR'%>
    <div class="field">
      <%= form.label :add_to_draft %>
      <%= form.check_box :post_type, { checked: false }, 'C', 'AR' %>
    </div>
  <% elsif post.post_type == 'R'%>
    <div class="field">
      <%= form.label :add_to_draft %>
      <%= form.check_box :post_type, { checked: false }, 'C', 'R' %>
    </div>
  <% else %>
    <div class="field">
      <%= form.label :add_to_moderation %>
      <%= form.check_box :post_type, { checked: false }, 'M', 'C' %>
    </div>
  <% end %>

  <%= form.submit "Draft", class: 'btn btn-lg btn-primary float-right' %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<div class="wrapper fadeInDown">
  <div id="f">
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<br>
<% @posts.each do |post| %>

  <section class="" style="background-color: #fbfbfb; border-radius: .5rem .5rem 0 0;margin:0 50px 0 50px;//top right bottom left">

    <div class="card px-3 pt-3" style="max-width: 32rem;    margin: auto;
      width: 50%;
      padding: 10px;">
      <% if post.tags.any? %>
        <p><small>Tags: <%= raw post.tags.map(&:name).map { |t| link_to t, ftags_path(t) }.join(', '); %></small></p>
      <% end %>

      <h5><%= post.title %></h5>

      <p>
        <%= post.content %>
      </p>

      <hr/>
      <%= link_to 'Show', post %>
      <td>
        <% if can? :update, post %>
          <a href=<%= edit_post_path(post) %>>Edit Post</a>
          <%= link_to 'Edit', edit_post_path(post) %>
        <% end %>

        <% if can? :destroy, post %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>

    </div>

    <br>

  </section>
<% end %>

<nav class="my-4">
  <ul class="pagination pagination-circle justify-content-center">
    <%= will_paginate @posts, :container => false %>
  </ul>
</nav>

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class="wrapper fadeInDown">
  <div id="f">
<%= render 'form', post: @post %>

<%= link_to 'Back', interfaces_path %>
</div>

</div>

app/views/posts/show.html.erb
<br>
  <section class="" style="background-color: #fbfbfb; border-radius: .5rem .5rem 0 0;margin:0 50px 0 50px;//top right bottom left">

    <div class="card px-3 pt-3" style="max-width: 32rem;    margin: auto;
      width: 50%;
      padding: 10px;">
      <% if @post.tags.any? %>
        <p><small>Tags: <%= raw @post.tags.map(&:name).map { |t| link_to t, ftags_path(t) }.join(', '); %></small></p>
      <% end %>

      <h5><%= @post.title %></h5>

      <p>
        <%= @post.content %>
      </p>

      <strong>User: <%= @post.user.name %></strong>

      <hr/>

    </div>
    <br>

  </section>

<p id="notice"><%= notice %></p>