config/routes.rb
Rails.application.routes.draw do

  resources :interfaces
  devise_for :users
  scope '/admin' do
    resources :users
    resources :admincas
  end
  resources :posts
  resources :roles
  resources :users
  resources :tags
  get 'filter/:tag', to: 'posts#index', as: :ftags
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/interface.rb
class Interface < ApplicationRecord
end

app/controllers/interfaces_controller.rb
# frozen_string_literal: true

# Interfaces controller class
class InterfacesController < ApplicationController
  before_action :set_interface, only: %i[show edit update destroy]
  load_and_authorize_resource
  # GET /interfaces or /interfaces.json
  def index
    @draft = Post.where(post_type: 'C', user_id: current_user.id)
    @moderation = Post.where(post_type: 'M', user_id: current_user.id)
    @rejected = Post.where(post_type: 'R', user_id: current_user.id)
    @approved = Post.where(post_type: 'A', user_id: current_user.id)
    @archive = Post.where(post_type: 'AR', user_id: current_user.id)
  end

  # GET /interfaces/new
  def new
    @interface = Interface.new
  end

  # POST /interfaces or /interfaces.json
  def create
    @interface = Interface.new(interface_params)

    respond_to do |format|
      if @interface.save
        format.html { redirect_to interface_url(@interface), notice: 'Interface was successfully created.' }
        format.json { render :show, status: :created, location: @interface }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interfaces/1 or /interfaces/1.json
  def update
    respond_to do |format|
      if @interface.update(interface_params)
        format.html { redirect_to interface_url(@interface), notice: 'Interface was successfully updated.' }
        format.json { render :show, status: :ok, location: @interface }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @interface.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interfaces/1 or /interfaces/1.json
  def destroy
    @interface.destroy

    respond_to do |format|
      format.html { redirect_to interfaces_url, notice: 'Interface was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_interface
    @interface = Interface.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def interface_params
    params.fetch(:interface, {})
  end
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/views/interfaces/_form.html.erb
<%= simple_form_for @interface do |form| %>
  <% if interface.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interface.errors.count, "error") %> prohibited this interface from being saved:</h2>

      <ul>
        <% interface.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interfaces/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/interfaces/index.html.erb
<h1>New Post</h1>
<% if can? :create, Post %>
  <%= link_to 'New Item', new_post_path %>
<% end %>

<br>

<h1>Draft</h1>
<% @draft.each do |post| %>
  <section class="pb-4">
    <div class="bg-white border rounded-5">

      <section class="p-2 d-flex  w-100" style="background-color: #fbfbfb; border-radius: .5rem .5rem 0 0;">
        <!--Section: News of the day-->
        <div class="col-md-2 mb-2">
          <h4><strong>Post: <%= post.title %></strong></h4>
          <td><%= link_to 'Show', post %></td>

          <% if can? :update, post %>
            <%= link_to 'Edit', edit_post_path(post) %>
          <% end %>
          <td>
            <% if can? :destroy, post %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </div>
      </section>
    </div>
  </section>
<% end %>

<h1>Moderation</h1>

<% @moderation.each do |post| %>
  <section class="pb-4">
    <div class="bg-white border rounded-5">

      <section class="p-2 d-flex  w-100" style="background-color: #fbfbfb; border-radius: .5rem .5rem 0 0;">
        <!--Section: News of the day-->
        <div class="col-md-2 mb-2">
          <h4><strong>Post: <%= post.title %></strong></h4>
          <td><%= link_to 'Show', post %></td>
          <% if can? :destroy, post %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </section>
    </div>
  </section>
<% end %>

<h1>Rejected</h1>

<% @rejected.each do |post| %>
  <section class="pb-4">
    <div class="bg-white border rounded-5">

      <section class="p-2 d-flex w-100" style="background-color: #fbfbfb; border-radius: .5rem .5rem 0 0;">
        <!--Section: News of the day-->
        <div class="col-md-2 mb-2">
          <h4><strong>Post: <%= post.title %></strong></h4>
          <td><%= link_to 'Show', post %></td>
          <% if can? :update, post %>
            <%= link_to 'Edit', edit_post_path(post) %>
          <% end %>
          <% if can? :destroy, post %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </section>
    </div>
  </section>
<% end %>

<h1>Approved</h1>

<% @approved.each do |post| %>
  <section class="pb-4">
    <div class="bg-white border rounded-5">

      <section class="p-2 d-flex w-100" style="background-color: #fbfbfb; border-radius: .5rem .5rem 0 0;">
        <!--Section: News of the day-->
        <div class="col-md-2 mb-2">
          <h4><strong>Post: <%= post.title %></strong></h4>
          <td><%= link_to 'Show', post %></td>
          <% if can? :destroy, post %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </section>
    </div>
  </section>
<% end %>

<h1>Archive</h1>

<% @archive.each do |post| %>
  <section class="pb-4">
    <div class="bg-white border rounded-5">

      <section class="p-2 d-flex w-100" style="background-color: #fbfbfb; border-radius: .5rem .5rem 0 0;">
        <!--Section: News of the day-->
        <div class="col-md-2 mb-2">
          <h4><strong>Post: <%= post.title %></strong></h4>
          <td><%= link_to 'Show', post %></td>
          <% if can? :update, post %>
            <%= link_to 'Edit', edit_post_path(post) %>
          <% end %>
          <% if can? :destroy, post %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </section>
    </div>
  </section>

<% end %>

app/views/interfaces/new.html.erb
<h1>New Interface</h1>

<%= render 'form', interface: @interface %>

<%= link_to 'Back', interfaces_path %>

app/views/interfaces/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_interface_path(@interface) %> |
<%= link_to 'Back', interfaces_path %>