config/routes.rb
Rails.application.routes.draw do

  resources :interfaces
  devise_for :users
  scope '/admin' do
    resources :users
    resources :admincas
  end
  resources :posts
  resources :roles
  resources :users
  resources :tags
  get 'filter/:tag', to: 'posts#index', as: :ftags
  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ads</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container-fluid">
    <div class="navbar-brand">Ads</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <a class="nav-link" href=<%= posts_path %>>Home</a>

      <% if user_signed_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if !@current_user&.admin? %>
                <li><a class="dropdown-item" href=<%= interfaces_path %>>User interface</a></li>
              <% else %>
                <li><a class="dropdown-item" href=<%= admincas_path %>>Adminca</a></li>
                <li><a class="dropdown-item" href=<%= users_path %>>Change Users</a></li>
                <li><a class="dropdown-item" href=<%= roles_path %>>Change Roles</a></li>
                <li><a class="dropdown-item" href=<%= tags_path %>>Change Tags</a></li>
              <% end %>
              <li><a class="dropdown-item" href=<%= edit_user_registration_path %>>Edit profile</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <a class="dropdown-item" data-method="delete" href= <%= destroy_user_session_path %>>
                  Sign out
                </a>
              </li>
            </ul>
          </li>
        </ul>
      <% end %>
      <form class="d-flex">
        <% if !user_signed_in? %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link text-wrap" style="width: 5rem;" href=<%= new_user_registration_path %>>Sign up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-wrap" style="width: 5rem;" href=<%= new_user_session_path %>>Sign in</a>
            </li>
          </ul>
        <% end %>
        <% if user_signed_in? %>
          Signed in as: <%= current_user.email %><br>
          <%end %>
      </form>
    </div>
  </div>
</nav>


<div class="flex-container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <main>
    <%= yield %>
  </main>
</div>
</body>
</html>
<script>
    $('#post_tag_ids').chosen({
        allow_single_deselect: true,
        width: '100%'
    })
</script>